version: '3.8'
services:
  nginx:
    image: nginx:1.21.1
    working_dir: /local/nginx-php-cors
    ports:
      - ${PORT_NGINX:-8000}:80
    volumes:
      - .:/local/nginx-php-cors
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:8.0.8-fpm
    working_dir: /local/nginx-php-cors
    volumes:
      - .:/local/nginx-php-cors

